spring:
  profiles:
    active: local

custom:
  property:
    single: custom-property
    comlist: comma,separated,list,to,value
    ncp:
      id: api-idd
      key: api-key
      url: htts://ncp.com
# custom.property.single
# custom.property.comlist